add cloudcom2018 paper abstract
BeyondTheClouds/blog pull request #5
Opened 2018-09-28 07:56 UTC by msimonin

2018-09-28 08:13 UTC, rcherrueau requested changes

2018-09-28 08:13 UTC, rcherrueau commented on _posts/2018-09-27-scalability-and-locality-awareness-of-remote-procedure-calls.markdown
> +{::options parse_block_html="true" /}
Could you remove this line

2018-09-28 08:13 UTC, rcherrueau commented on _posts/2018-09-27-scalability-and-locality-awareness-of-remote-procedure-calls.markdown
> +<div class="abstract">
Idem

2018-09-28 08:13 UTC, rcherrueau commented on _posts/2018-09-27-scalability-and-locality-awareness-of-remote-procedure-calls.markdown
> +</div>
Idem

2018-09-28 08:13 UTC, rcherrueau commented on _posts/2018-09-27-scalability-and-locality-awareness-of-remote-procedure-calls.markdown
> +{::options parse_block_html="false" /}
Idem

2018-09-28 08:14 UTC, rcherrueau commented
It would be cool if you can add the link to the paper (thanks to a HAL ref, for instance)

2018-10-10 13:37 UTC, msimonin commented
Closing this in favor of #5

2018-10-10 13:37 UTC, closed without merging

2018-10-10 19:50 UTC, rcherrueau commented
@msimonin @jrbalderrama please ping me when the paper will be available on HAL. I will add the link to the paper at that time. Thanks

2018-10-10 20:21 UTC, msimonin commented
Here, 

https://hal.inria.fr/hal-01891567

----- Mail original -----
> De: "Ronan Cherrueau ⚓" <notifications@github.com>
> À: "BeyondTheClouds/blog" <blog@noreply.github.com>
> Cc: "Matthieu Simonin" <matthieu.simonin@inria.fr>, "Mention" <mention@noreply.github.com>
> Envoyé: Mercredi 10 Octobre 2018 21:50:16
> Objet: Re: [BeyondTheClouds/blog] add cloudcom2018 paper abstract (#5)

> @msimonin @jrbalderrama please ping me when the paper will be available on HAL.
> I will add the link to the paper at that time. Thanks
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/BeyondTheClouds/blog/pull/5#issuecomment-428707206

2018-10-11 13:09 UTC, rcherrueau commented
Thanks, the post has been updated, see c149949d469328f94e7a7eb62ea1782c794287e8.